Helper Functions
--------------------


.. currentmodule:: shape_generator.helpers

.. autosummary::
    csv
    deg2slope
    channel_end
    combine_input_files
    Slope
    Vertical
    Horizontal
    Circle

.. automodule:: shape_generator.helpers
    :members: csv, deg2slope

.. autofunction:: shape_generator.helpers.channel_end
.. autofunction:: shape_generator.helpers.combine_input_files


.. rubric:: Class Functions

.. autoclass:: shape_generator.helpers.Slope
    :members:

.. autoclass:: shape_generator.helpers.Vertical
    :members:

.. autoclass:: shape_generator.helpers.Horizontal
    :members:

.. autoclass:: shape_generator.helpers.Circle
    :members:
