Helper Functions
--------------------


.. currentmodule:: shape_generator.helpers

.. autosummary::
    csv
    deg2slope
    linear
    circle
    channel_end
    combine_input_files

.. automodule:: shape_generator.helpers
    :members: csv, deg2slope

.. figure:: images/slope.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Slope

.. autofunction:: shape_generator.helpers.linear

.. figure:: images/gerade.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Straight line

.. autofunction:: shape_generator.helpers.circle

.. figure:: images/kreis.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Circle

.. autofunction:: shape_generator.helpers.channel_end

.. figure:: images/channel_end.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Channel end

.. autofunction:: shape_generator.helpers.combine_input_files