Main Function
--------------------

.. currentmodule:: shape_generator.shape_generator.CrossSection

.. rubric:: Class

.. autosummary::
    shape_generator.shape_generator.CrossSection

.. rubric:: Methods

.. autosummary::
    __init__
    add
    check_for_slopes
    create_point_cloud
    check_point_cloud
    df_rel
    cross_section_area

.. rubric:: Macros

.. autosummary::
    generator
    make
    add_and_show

.. rubric:: Text-files / Figures

.. autosummary::
    profile_rel_plot
    profile_abs_plot
    profile_abs_figure
    dat_file
    inp_string
    input_file

.. rubric:: Pre defined Cross Sections

.. autosummary::
    standard
    box
    box_from_string
    from_point_cloud

.. autoclass:: shape_generator.shape_generator.CrossSection
    :members:
