Helper Functions
--------------------

.. automodule:: shape_generator.helpers
    :members: csv, deg2slope

.. figure:: images/slope.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Slope

.. automodule:: shape_generator.helpers
    :members: linear

.. figure:: images/gerade.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Straight line

.. automodule:: shape_generator.helpers
    :members: circle

.. figure:: images/kreis.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Circle

.. automodule:: shape_generator.helpers
    :members: channel_end

.. figure:: images/channel_end.gif
    :align: center
    :alt: make_shape
    :figclass: align-center

    Channel end

.. automodule:: shape_generator.helpers
    :members: combine_input_files